name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run test
        run: |
          set -xe
          go test
          go test -race
        env:
          GO111MODULE: "on"

      - name: Run lint
        run: |
          set -xe
          export GOPATH=`go env GOPATH`
          export PATH=$GOPATH/bin:$PATH
          ! gofmt -d . | grep '^'
          go get -v -t -d ./...
          go get -u golang.org/x/lint/golint
          golint -set_exit_status

      - name: Slack Notification
        uses: homoluctus/slatify@v1.0
        if: always()
        with:
          job_name: '*go build*'
          type: ${{ job.status }}
          channel: ${{ secrets.SLACK_CHANNEL }}
          icon_emoji: ":octocat:"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
